### ISSUE TITLE
Bug Report: Compatibility Issue with VTK 9.4.0

### ISSUE THREAD

**Issue by elide-b** [MICA-MNI/BrainSpace#128]
After upgrading to VTK version 9.4.0, the brainspace package no longer works as expected. Specifically, the example from the documentation

```
from brainspace.datasets import load_conte69

# and load the conte69 surfaces
surf_lh, surf_rh = load_conte69()
print(surf_lh.n_points)
```

fails with 

```
Traceback (most recent call last):
  File "/home/marialaura/articolo/prova.py", line 4, in <module>
    surf_lh, surf_rh = load_conte69()
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/datasets/base.py", line 167, in load_conte69
    surfs[i] = read_surface(ipth.format(side))
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/mesh/mesh_io.py", line 144, in read_surface
    return get_output(reader, update=update, as_data=return_data)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/decorators.py", line 41, in _wrapper_wrap
    data = func(*args, **kwds)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/pipeline.py", line 170, in get_output
    return to_data(ftr, port=port)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/decorators.py", line 41, in _wrapper_wrap
    data = func(*args, **kwds)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/pipeline.py", line 135, in to_data
    out[i] = ftr.GetOutputDataObject(port_id)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/wrappers/base.py", line 35, in __call__
    return _wrap_output_data(self.name(*args, **kwargs))
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/wrappers/base.py", line 515, in _wrap_output_data
    return wrap_vtk(data)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/wrappers/base.py", line 475, in wrap_vtk
    wobj = BSWrapVTKObject(obj)
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/wrappers/base.py", line 386, in BSWrapVTKObject
    for c in [sc.__vtkname__[3:] for sc in obj.__class__.mro()[:-3]]:
  File "/home/marialaura/tvmb/lib/python3.8/site-packages/brainspace/vtk_interface/wrappers/base.py", line 386, in <listcomp>
    for c in [sc.__vtkname__[3:] for sc in obj.__class__.mro()[:-3]]:
AttributeError: type object 'PointSet' has no attribute '__vtkname__'
```

**Comment by victoris93** [comment]
Same here

**Comment by zihuaihuai** [comment]
Thanks for bring this up, this new issues with 9.4.0 has been fixed
