### ISSUE TITLE
VTK error when running example data

### ISSUE THREAD

**Issue by HusBunia** [MICA-MNI/BrainSpace#51]
Hi: 
An error has occurred when I running the example data, 
Traceback (most recent call last):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 203, in __getattr__
    return VTKMethodWrapper(super().__getattr__(name))
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\vtkmodules\numpy_interface\dataset_adapter.py", line 130, in __getattr__
    return getattr(self.VTKObject, name)
AttributeError: 'vtkmodules.vtkCommonDataModel.vtkPolyData' object has no attribute '__len__'

My system is win10, and vtk version is 9.0.3. Could you tell me how to solve the problem

Thanks

**Comment by OualidBenkarim** [comment]
Hi @HusBunia 

what example are you trying to run? And please provide more info about the error

**Comment by HusBunia** [comment]
> Hi @HusBunia
> 
> what example are you trying to run? And please provide more info about the error

Hi  @OualidBenkarim

"I ran the first command ' surf_lh, surf_rh = load_conte69()', and it returns the error : 
Traceback (most recent call last):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 203, in __getattr__
    return VTKMethodWrapper(super().__getattr__(name))
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\vtkmodules\numpy_interface\dataset_adapter.py", line 130, in __getattr__
    return getattr(self.VTKObject, name)
AttributeError: 'vtkmodules.vtkCommonDataModel.vtkPolyData' object has no attribute '__len__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 274, in frame_vars_to_struct
    value = var_to_struct(v, str(k), evaluate_full_value=eval_full_val)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 358, in var_to_struct
    elif hasattr(v, '__len__') and not is_string(v):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 205, in __getattr__
    return self._handle_call('get', name, None)
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 171, in _handle_call
    method = self.vtk_map[key][name.lower()]
KeyError: '__len__'
Unexpected error, recovered safely.
Traceback (most recent call last):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 203, in __getattr__
    return VTKMethodWrapper(super().__getattr__(name))
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\vtkmodules\numpy_interface\dataset_adapter.py", line 130, in __getattr__
    return getattr(self.VTKObject, name)
AttributeError: 'vtkmodules.vtkCommonDataModel.vtkPolyData' object has no attribute '__len__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 274, in frame_vars_to_struct
    value = var_to_struct(v, str(k), evaluate_full_value=eval_full_val)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 358, in var_to_struct
    elif hasattr(v, '__len__') and not is_string(v):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 205, in __getattr__
    return self._handle_call('get', name, None)
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\brainspace\vtk_interface\wrappers\base.py", line 171, in _handle_call
    method = self.vtk_map[key][name.lower()]
KeyError: '__len__'
Unexpected error, recovered safely."

I'm not familiar with how the VTK is working. And I have tried to load only left or right surface file, it could be loaded in turn. But the next command "surf_lh.n_points" returns the error:

 "Traceback (most recent call last):
  File "C:\Users\11481\PycharmProjects\untitled\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-cf18ed3c9642>", line 1, in <module>
    surf_lh.n_points
AttributeError: 'tuple' object has no attribute 'n_points' "

That's all of the error information I have met. Thanks for your help!

**Comment by OualidBenkarim** [comment]
That's definitely an issue with vtk. You can try with using vtk 8.2 instead

**Comment by HusBunia** [comment]
> That's definitely an issue with vtk. You can try with using vtk 8.2 instead

Thanks for your reply! I'll try a new version of VTK
